### ISSUE TITLE
Disappears text when updating

### ISSUE THREAD

**Issue by yequid-old** [Creeperface01/ScoreboardAPI#3]
When the value is “true”, the “Balance” line disappears, when “false”, the line with the text “site.ru” disappears
![Annotation](https://user-images.githubusercontent.com/51378109/61226548-48e65e00-a72b-11e9-975d-8edc3e05a189.png)
![Annotation_1](https://user-images.githubusercontent.com/51378109/61226549-497ef480-a72b-11e9-8ea1-3a1a79ea47be.png)

**Comment by Creeperface01** [comment]
What is the difference between those 3 when cases?

**Comment by yequid-old** [comment]
> What is the difference between those 3 when cases?

Site color changes and the balance is updated.

**Comment by Creeperface01** [comment]
@yequid I can't reproduce it. Can you post some code snippet?

**Comment by yequid-old** [comment]
> @yequid I can't reproduce it. Can you post some code snippet?

https://pastebin.com/qKAK7Tjv

**Comment by Creeperface01** [comment]
still can't reproduce. Are you sure you have the latest version? Eventually you can try this one


[ScoreboardAPI-1.0.zip](https://github.com/Creeperface01/ScoreboardAPI/files/3411514/ScoreboardAPI-1.0.zip)
