### ISSUE TITLE
In the feature/1.16 can result in client disconnect

### ISSUE THREAD

**Issue by lt-name** [Creeperface01/ScoreboardAPI#5]
(Sorry i can only use google translate)

When I use the nukkitx feature/1.16 branch, will appear this warning,The player will then disconnect.
Received packet violation warning: PacketViolationWarningPacket(type=MALFORMED_PACKET, severity=FINAL_WARNING, packetId=108, context=)
This is the method I use ScoreboardAPI:
https://github.com/lt-name/MurderMystery_Nukkit/blob/master/src/main/java/cn/lanink/lib/scoreboard/ScoreboardGt.java
Usually appears when the scoreboard content changes.

**Comment by Creeperface01** [comment]
Fixed
